services:
  - type: web
    name: agria
    runtime: node
    plan: free
    region: singapore
    branch: develop
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
